apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/opendatahub-io/ai-gateway-payload-processing?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "group-test"
    pipelinesascode.tekton.dev/on-comment: "^/group-test"
  name: ai-gateway-group-test
  namespace: open-data-hub-tenant
  labels:
    appstudio.openshift.io/application: group-testing
    appstudio.openshift.io/component: ai-gateway-group
    pipelines.appstudio.openshift.io/type: test
spec:
  params:
  - name: group-components
    value: '{ "odh-ai-gateway-payload-processing-ci": "opendatahub/odh-ai-gateway-payload-processing", "ai-gateway-payload-processing-e2e-ci": "opendatahub/ai-gateway-payload-processing-e2e" }'
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/opendatahub-io/odh-konflux-central.git
    - name: revision
      value: main
    - name: pathInRepo
      value: integration-tests/ai-gateway-payload-processing/pr-group-testing-pipeline.yaml
  taskRunTemplate:
    podTemplate:
      nodeSelector:
        konflux-ci.dev/workload: konflux-tenants
      tolerations:
      - effect: NoSchedule
        key: konflux-ci.dev/workload
        operator: Equal
        value: konflux-tenants
    serviceAccountName: konflux-integration-runner
  timeouts:
    pipeline: 4h0m0s
    tasks: 3h
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'